# Site settings
title: Static Themes
email: scott@staticthemes.io
description: Static themes sells themes for static site generators - Jekyll, Hugo, Hexo, Middleman, etc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://staticthemes.io" # the base hostname & protocol for your site
twitter_username: staticthemes

# Build settings
markdown: kramdown
